AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Creates RDS database with public access using imports from network.yml and securitygroups.yml
Parameters:
  ProjectName:
    Description: "Name of Project"
    Type: String
    Default: "udapeople"
  RDSPassword:
    Description: "Password for RDS User"
    Type: String
    MinLength: 8
    MaxLength: 30
    NoEcho: true
Resources:
  rdsDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Only Public Networks"
      SubnetIds:
        - !Select [0, !Split [",", !ImportValue network-PublicSubnets]]
        - !Select [1, !Split [",", !ImportValue network-PublicSubnets]]
  rdsDBInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      AllocatedStorage: "10"
      AvailabilityZone: !Select [0, !GetAZs '']
      DBInstanceIdentifier: !Sub "${ProjectName}-rds"
      DBName: !Sub "${ProjectName}"
      DBInstanceClass: db.t2.micro
      DBSubnetGroupName: !Ref rdsDBSubnetGroup
      Engine: postgres
      EngineVersion: 9.6.5
      MasterUsername: postgres
      MasterUserPassword: !Ref RDSPassword
      PubliclyAccessible: true
      VPCSecurityGroups: 
        - !ImportValue rdsPostgresSecurityGroup
    DeletionPolicy: "Retain"
    UpdateReplacePolicy: "Retain"
  
      
Outputs:
  rdsDbEndpoint:
    Description: RDS DB Endpoint
    Value: !Join [":",[!GetAtt rdsDBInstance.Endpoint.Address, !GetAtt rdsDBInstance.Endpoint.Port ] ]

  rdsDBInstance:
    Description: RDS DB
    Value: !Ref rdsDBInstance
    Export: 
      Name: rdsDbInstance



