---
- name: Git checkout
  git:
    repo: 'https://github.com/meluzovm/udacity-devops-cicd.git'
    version: circleci-project-setup
    dest: /home/ubuntu/git
    force: yes

- name: Install dependencies
  shell: |
    cd /home/ubuntu/git/backend
    npm install

- name: Build Backend
  become: true
  shell: |
    cd /home/ubuntu/git/backend
    npm run build

- name: Prepare environment
  shell: |
    export ENVIRONMENT="{{ lookup('env','ENVIRONMENT') }}"
    export TYPEORM_CONNECTION="{{ lookup('env','TYPEORM_CONNECTION') }}"
    export TYPEORM_HOST="{{ lookup('env', 'TYPEORM_HOST') }}"
    export TYPEORM_PORT="{{ lookup('env','TYPEORM_PORT') }}"
    export TYPEORM_ENTITIES="{{ lookup('env', 'TYPEORM_ENTITIES') }}"
    export TYPEORM_USERNAME="{{ lookup('env', 'TYPEORM_USERNAME') }}"
    export TYPEORM_PASSWORD="{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    export TYPEORM_DATABASE="{{ lookup('env', 'TYPEORM_DATABASE') }}"
    env | grep TYPEORM

- name: Run PM2
  shell:
    cd /home/ubuntu/git/backend
    ls -la
    pm2 start npm -- run start