---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: udapeople-rds.cpo019hf7dp7.eu-central-1.rds.amazonaws.com
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: postgres
    TYPEORM_PASSWORD: QQqq1234
    TYPEORM_DATABASE: postgres
  
  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
        delay: 5
        timeout: 600    #fix to 600

  
  #  - name: "install python for Ansible."
  #    # Your code here

  roles:
    # Your code here
    - configure-server